# Generated by Django 4.1.1 on 2022-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_review_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_Link',
            new_name='demo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='defaulr.jpg', null=True, upload_to=''),
        ),
    ]
